# This file was generated by GoReleaser. DO NOT EDIT.
cask "escape-cli" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "9bdfa9551b0d2e3c015eebe4e1a08ebf1c607e20983da67d445c2a7fe6ed17a6"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "17c947a09483046748cb94156f18684734548925a0cff98618422fafa3e46968"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6cca96d48e6e0cce689bf6f2e9c6e7894d9b5d96ef0dd529f6fd2f9863e403f6"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf63a78d6fb872565afc4b74861d5ac4d4b6877ed482afdebba5d7480cce35da"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "escape-cli"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "escape-cli"

  # No zap stanza required

end
