# This file was generated by GoReleaser. DO NOT EDIT.
cask "escape-cli" do
  version "1.3.6"

  on_macos do
    on_intel do
      sha256 "1865857e59ca15c35684c43955e56992374947f6f7443170ac1feff742478e17"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3275c04fe49b0ce14e4c4e70cf317e33b065a02b654f27b3c0583ddc779a0dd"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92d3cd104f6e2ac7a175735acbf87dfed8c0add9a757f68b87ddf8ef0ac91841"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bed537dba1e9e019a55bacf1875050f197c92b5e4fe01163fdc19c01b296663"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "escape-cli"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "escape-cli"

  # No zap stanza required

end
