# This file was generated by GoReleaser. DO NOT EDIT.
cask "escape-cli" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "fa3976057b7f5502fd592e7bfe4b8f36f92a1f93efc04875ae424c55b19351b8"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1c5dee3fb95375647c0b57609794c573272e9e5e3d3add29ee6a57d0b8cb468"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba63a1256f4a7342effab2a23630e2d732609c0104de5d4c370649218f97059e"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0ed432464e275f66719fd8d0df6be7a0b2e4d6b2acae15e19c7c12e0e1f4cfaa"
      url "https://github.com/Escape-Technologies/cli/releases/download/v#{version}/cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "escape-cli"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "escape-cli"

  # No zap stanza required

end
